"""empty message

Revision ID: 823405ed40f3
Revises: fc8c3133aed5
Create Date: 2018-09-21 21:59:38.294921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823405ed40f3'
down_revision = 'fc8c3133aed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('enquirer_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.create_foreign_key(None, 'enquiries', 'users', ['enquirer_id'], ['user_id'])
    op.drop_column('enquiries', 'enquirer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('enquirer', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.create_foreign_key(None, 'enquiries', 'users', ['enquirer'], ['user_id'])
    op.drop_column('enquiries', 'enquirer_id')
    # ### end Alembic commands ###
